package eladkay.ellipticcurve.mathengine

// These are the elliptic curves the MAN wants you to be using!
// https://safecurves.cr.yp.to/


/**
 * This class defines a standardized elliptic curve using standard parameters, according to the RFC5639:
 * p is the modulus; a and b are the coefficients; g is the initial point for cryptography; q is the prime order of the
 * group generated by g and h is the cofactor of g on the curve.
 */
data class StandardEllipticCurve(val p: Long, val a: Long, val b: Long, val g: Vec2l, val q: Long, val h: Long, val id: String): FiniteEllipticCurve(a, b, p)

//https://tools.ietf.org/html/rfc5639
//val brainpoolP160r1 = StandardEllipticCurve(0xE95E4A5F737059DC60DFC7AD95B3D8139515620F)